"""
Builds the two reference files the tracker ships with:

  data/coast.mjs    - land polygons used to estimate where a forecast track
                      first crosses the shoreline
  public/data/places.json - coastal towns used for the "points along the coast" table

Sources (all public):
  - U.S. Census Bureau cartographic boundaries, states at 1:500,000
    (includes barrier islands such as Santa Rosa Island and Perdido Key)
  - Natural Earth 10m land and minor islands (outside the United States)
  - Natural Earth 10m populated places (towns outside the United States)
  - U.S. Census Bureau 2023 Gazetteer, places (cities, towns, and census-designated
    places such as Navarre)

Run:  python3 tools/build_data.py <cache-dir>
Needs: pip install shapely pyshp
"""
import csv
import io
import json
import os
import re
import sys
import urllib.request
import zipfile

import shapefile
from shapely.geometry import Point, box, mapping, shape
from shapely.ops import unary_union
from shapely.strtree import STRtree

SOURCES = {
    "census": "https://www2.census.gov/geo/tiger/GENZ2023/shp/cb_2023_us_state_500k.zip",
    "ne_land": "https://raw.githubusercontent.com/nvkelso/natural-earth-vector/master/geojson/ne_10m_land.geojson",
    "ne_islands": "https://raw.githubusercontent.com/nvkelso/natural-earth-vector/master/geojson/ne_10m_minor_islands.geojson",
    "ne_places": "https://raw.githubusercontent.com/nvkelso/natural-earth-vector/master/geojson/ne_10m_populated_places_simple.geojson",
    "gazetteer": "https://www2.census.gov/geo/docs/maps-data/data/gazetteer/2023_Gazetteer/2023_Gaz_place_national.zip",
}

# Region the tracker covers: Atlantic, Caribbean, Gulf, and the eastern Pacific coast.
REGION = box(-125.0, 5.0, -55.0, 50.0)
SKIP_STATES = {"AK", "HI", "GU", "MP", "AS", "VI"}
COASTAL_KM = 15.0          # a town counts as "coastal" if this close to the shoreline
SIMPLIFY_DEG = 0.001       # about 100 m; keeps barrier islands


def fetch(cache, key):
    path = os.path.join(cache, os.path.basename(SOURCES[key]))
    if not os.path.exists(path):
        print("downloading", SOURCES[key])
        urllib.request.urlretrieve(SOURCES[key], path)
    return path


def rnd(coords):
    return [[round(x, 4), round(y, 4)] for x, y in coords]


def main(cache):
    os.makedirs(cache, exist_ok=True)

    # --- United States land (Census, shoreline-clipped) ---
    zpath = fetch(cache, "census")
    with zipfile.ZipFile(zpath) as z:
        z.extractall(os.path.join(cache, "census"))
    shp = os.path.join(cache, "census", "cb_2023_us_state_500k.shp")
    us_parts = []
    for sr in shapefile.Reader(shp).shapeRecords():
        if sr.record["STUSPS"] in SKIP_STATES:
            continue
        us_parts.append(shape(sr.shape.__geo_interface__))
    us = unary_union(us_parts).intersection(REGION)
    us_cover = us.buffer(0.15)

    # --- Everything else (Natural Earth), with the U.S. cut out ---
    other_parts = []
    for key in ("ne_land", "ne_islands"):
        for f in json.load(open(fetch(cache, key)))["features"]:
            g = shape(f["geometry"])
            if g.intersects(REGION):
                other_parts.append(g.intersection(REGION))
    other = unary_union(other_parts).difference(us_cover)

    land = unary_union([us, other]).simplify(SIMPLIFY_DEG, preserve_topology=True)

    polys = []
    for g in getattr(land, "geoms", [land]):
        if g.geom_type != "Polygon" or g.area < 1e-7:
            continue
        minx, miny, maxx, maxy = g.bounds
        polys.append({
            "b": [round(minx, 4), round(miny, 4), round(maxx, 4), round(maxy, 4)],
            "r": [rnd(g.exterior.coords)] + [rnd(i.coords) for i in g.interiors],
        })
    os.makedirs("data", exist_ok=True)
    os.makedirs("public/data", exist_ok=True)
    coast = json.dumps({"source": "U.S. Census cb_2023_us_state_500k; Natural Earth 10m land (outside U.S.)",
                        "polygons": polys}, separators=(",", ":"))
    with open("data/coast.mjs", "w") as fh:
        fh.write("// Generated by tools/build_data.py. Land polygons for the coast-crossing estimate.\n")
        fh.write("export default " + coast + ";\n")
    print("coast polygons", len(polys))

    # --- Coastal towns ---
    shore = land.boundary
    lines = list(getattr(shore, "geoms", [shore]))
    tree = STRtree(lines)

    def km_to_shore(lon, lat):
        p = Point(lon, lat)
        idx = tree.nearest(p)
        return lines[idx].distance(p) * 111.0

    places = []
    seen = set()
    gz = fetch(cache, "gazetteer")
    with zipfile.ZipFile(gz) as z:
        text = z.read(z.namelist()[0]).decode("utf-8")
    suffix = re.compile(r" (city|town|village|CDP|borough|municipality|city and borough|comunidad|zona urbana)$")
    for row in csv.DictReader(io.StringIO(text), delimiter="\t"):
        row = {k.strip(): v.strip() for k, v in row.items()}
        if row["USPS"] in SKIP_STATES:
            continue
        lat, lon = float(row["INTPTLAT"]), float(row["INTPTLONG"])
        if not REGION.contains(Point(lon, lat)):
            continue
        name = suffix.sub("", row["NAME"])
        key = (name, row["USPS"])
        if key in seen:
            continue
        if km_to_shore(lon, lat) <= COASTAL_KM:
            seen.add(key)
            places.append([name, row["USPS"], round(lat, 4), round(lon, 4)])
    us_count = len(places)
    for f in json.load(open(fetch(cache, "ne_places")))["features"]:
        p = f["properties"]
        if p.get("adm0_a3") == "USA":
            continue
        lon, lat = f["geometry"]["coordinates"]
        if not REGION.contains(Point(lon, lat)):
            continue
        if km_to_shore(lon, lat) <= COASTAL_KM:
            places.append([p["name"], p.get("adm0name") or p.get("sov0name") or "", round(lat, 4), round(lon, 4)])
    with open("public/data/places.json", "w") as fh:
        json.dump({"source": "U.S. Census 2023 Gazetteer places (U.S.); Natural Earth populated places (elsewhere)",
                   "fields": ["name", "region", "lat", "lon"], "places": places}, fh, separators=(",", ":"))
    print("coastal places", us_count, "U.S.,", len(places) - us_count, "elsewhere")


if __name__ == "__main__":
    main(sys.argv[1] if len(sys.argv) > 1 else ".cache")
